In [26]:
import numpy as np

# Rating matrix R, where rows correspond to users and columns to movies
R = np.array([
    [5, 3, 5, 5, 2, 1],
    [4, 4, 4, 4, 1, 0],
    [3, 3, 4, 5, 0, 0],
    [4, 2, 5, 4, 0, 0],
    [1, 0, 1, 0, 5, 5],
    [0, 0, 1, 2, 4, 5],
    [0, 0, 0, 0, 4, 3],
    [1, 0, 1, 1, 5, 4]
])

# Perform SVD
U, Sigma, VT = np.linalg.svd(R, full_matrices=False)

# Retained energy percentage for the first two singular values
total_energy = np.sum(Sigma**2)
retained_energy = np.sum(Sigma[:2]**2)
RE_percent = (retained_energy / total_energy) * 100

# Reconstruct the matrix using only the first two singular values
U_reduced = U[:, :2]
Sigma_reduced = np.diag(Sigma[:2])
VT_reduced = VT[:2, :]
V_reduced = VT.T[:, :2]
R_hat = U_reduced @ Sigma_reduced @ VT_reduced

# Calculate Mean Square Error (MSE)
MSE = np.mean((R - R_hat) ** 2)

# Output the reduced matrices and metrics
print("U_reduced:\n", U_reduced)
print("Sigma_reduced:\n", Sigma_reduced)
print("V_reduced:\n", V_reduced)
print("VT_reduced:\n", VT_reduced)
print("Retained Energy Percentage (RE%):", RE_percent)
print("Mean Square Error (MSE):", MSE)
#REMEMBER, R = U * Sigma *VT , R(reduced rank) = U_reduced, Sigma_reduced, VT_reduced
#REMEMBER, V_reduced is displayed here only for the purposes of concept space calculations

U_reduced:
 [[-0.54360657  0.12523598]
 [-0.44337089  0.20514606]
 [-0.41081768  0.24411384]
 [-0.41888848  0.24188427]
 [-0.21332469 -0.52095791]
 [-0.22997204 -0.448301  ]
 [-0.11111531 -0.3868991 ]
 [-0.23007443 -0.44952155]]
Sigma_reduced:
 [[17.099392    0.        ]
 [ 0.         11.81291776]]
V_reduced:
 [[-0.45866675  0.18421895]
 [-0.32015953  0.20421731]
 [-0.52063844  0.18741013]
 [-0.52114001  0.1937495 ]
 [-0.29895385 -0.65501004]
 [-0.23472963 -0.65012237]]
VT_reduced:
 [[-0.45866675 -0.32015953 -0.52063844 -0.52114001 -0.29895385 -0.23472963]
 [ 0.18421895  0.20421731  0.18741013  0.1937495  -0.65501004 -0.65012237]]
Retained Energy Percentage (RE%): 97.94427048592482
Mean Square Error (MSE): 0.18887014910565678


## Concept space and cosine similarity for new users (all matrices are in fact the same as above)

In [27]:
import numpy as np

# Re-define the rating matrix R and user vectors for George and Robert
R = np.array([
    [5, 3, 5, 5, 2, 1],
    [4, 4, 4, 4, 1, 0],
    [3, 3, 4, 5, 0, 0],
    [4, 2, 5, 4, 0, 0],
    [1, 0, 1, 0, 5, 5],
    [0, 0, 1, 2, 4, 5],
    [0, 0, 0, 0, 4, 3],
    [1, 0, 1, 1, 5, 4]
])
george_vector = np.array([0, 4, 5, 0, 0, 1])
robert_vector = np.array([0, 1, 0, 0, 4, 0])



# Project George's and Robert's vectors into the reduced space
george_concept = george_vector @ VT_reduced.T
robert_concept = robert_vector @ VT_reduced.T

# Calculate cosine similarity between the projected vectors
from numpy.linalg import norm
cosine_similarity = np.dot(george_concept, robert_concept) / (norm(george_concept) * norm(robert_concept))

# Outputs
print("george concept", george_concept)
print("robert concept", robert_concept)
print("cosine similarity", cosine_similarity)



george concept [-4.11855993  1.10379749]
robert concept [-1.51597493 -2.41582285]
cosine similarity 0.294141004123567


###  RECOMMENDATION LIST FOR THE USER !!!

### We find the dot product of the user's concept space with V^T so as to map the user's representation to  movie space

In [28]:
#Recommendation list for George

print("Recommendation list for George:", george_concept @ VT_reduced)

Recommendation list for George: [2.0923869  1.54401076 2.35114343 2.36020656 0.50826091 0.24914459]
